version: '3.7'

services:
  mongodb-primary:
    image: bitnami/mongodb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_master_data:/bitnami'

volumes:
  mongodb_master_data:
    driver: local
